chore: implemented apis to import members from third party providers
onculture-build/OnCulture-Backend-V2 pull request #56
Opened 2024-10-04 06:52 UTC by Kaydayo

## Description

[Describe the change that was made in this PR]

### Todos

- [ ] Tested and working locally
- [ ] Unit tests added (if appropriate)
- [ ] Code changes documented
- [x] Requested review from >=1 devs on the team

### How to test

[Add detailed steps to test the changes that have been made]

### Screenshots and/or Gifs

[Insert screenshots and/or gifs showing the graphic representation of the change]

### Associated JIRA Tasks

- [Task Code: Task Description](http://jira_task_link.com)

### Known Issues

[Describe any known issue with this change]

2024-10-06 21:10 UTC, ayopedro requested changes

2024-10-06 21:10 UTC, ayopedro commented on src/common/third-party/interfaces/index.ts
> +  image: string;
are we setting their image to be the same on slack?

2024-10-06 21:10 UTC, ayopedro commented on src/common/third-party/providers/slack/slack-integration.ts
> +    console.log(config['slackAccessToken'], "all good")
remove logger if not in use

2024-10-06 21:10 UTC, ayopedro commented on src/common/third-party/providers/slack/slack-integration.ts
> +      }).filter((item)=> item.email);
you can use reduce here instead of map and filter.

2024-10-06 21:10 UTC, ayopedro commented on src/company/integrations/integrations.controller.ts
>    @AuthStrategy(AuthStrategyType.JWT)
use this strategy on the entire controller class instead of putting it on each controller endpoint.

2024-10-06 21:12 UTC, Kaydayo commented on src/common/third-party/interfaces/index.ts
> +  image: string;
yup

2024-10-07 06:09 UTC, ayopedro approved these changes

2024-10-07 07:18 UTC, merged